### ISSUE TITLE
'constructor' and zoom issue

### ISSUE THREAD

**Issue by Shane98c** [rte-antares-rpackage/leaflet.minichart#1]
Hello!  This looks to be a great library!  I'm getting an odd error currently though.  

I've reduced my code to the bare minimum from your example and I'm still getting it, so I've decided to post it here. 

error: 
```
leaflet.minichart.min.js:10 Uncaught TypeError: Cannot read property 'constructor' of undefined
    at Object.c [as toArray] (leaflet.minichart.min.js:10)
    at e._redraw (leaflet.minichart.min.js:10)
    at e.onAdd (leaflet.minichart.min.js:10)
    at e._layerAdd (leaflet.js:6)
    at e.whenReady (leaflet.js:6)
    at e.addLayer (leaflet.js:6)
    at testchart.html:23
```

Basic code to reproduce the error: 
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.2/dist/leaflet.css" media="screen" title="leaflet">
    <script src="https://unpkg.com/leaflet@1.0.2/dist/leaflet.js" charset="utf-8"></script>
    <script src="https://unpkg.com/leaflet.minichart@0.2.0/dist/leaflet.minichart.min.js" charset="utf-8"></script>
  </head>
  <body>
    <div id="map" style="width:100%;height:400px;"></div>
    <script>
      var center = [48.861415, 2.349326];

      var mymap = L.map('map').setView(center, 13);
      L.tileLayer('http://a.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(mymap);

      function fakeData() {
        return [Math.random(), Math.random(), Math.random()];
      }

      var myBarChart = L.minichart(center, {data: fakeData()});
      mymap.addLayer(myBarChart);

      setInterval(function() {
        myBarChart.setOptions({data: fakeData()})
      }, 2000);
    </script>
  </body>
</html>
```

**Comment by Shane98c** [comment]
As usual, posting an issue leads to figuring out the issue 15 minutes later.  Turns out the `maxValues` attribute needs to be used.  

So: 
`var myBarChart = L.minichart(center, {data: fakeData()});`
should be 
`var myBarChart = L.minichart(center, {data: fakeData(), maxValues: 1});`

However, now I'm running into a different issue: the graph is not staying anchored on its coordinates during zoom events.  I see it does in your examples here: https://rte-antares-rpackage.github.io/leaflet.minichart/tutorial-PISA%20scores.html So maybe it has to do with a recent leaflet update (using 1.0.2 in the above examples from the readme)

Thanks much for putting this library together!

**Comment by FrancoisGuillem** [comment]
Thank you for the feedback. I use leaflet 0.7.2 in the example so I did not notice these problems. I will fix that as soon as possible.

**Comment by FrancoisGuillem** [comment]
Both problems should be fixed now: `maxValues` should not be required anymore and charts should be correctly positioned after zoom. Could you confirm it is OK now ?

**Comment by Shane98c** [comment]
@FrancoisGuillem Thanks so much for the fast fix!  All seems to be working great now.  

There's one small error in the current readme btw.  in the first `Math.random` the word random is capitalized, causing a small error.  

Thanks again for the help with this!
